export const ERROR = {
  noPhoto: "写真を探せませんでした。",
  noComment: "コメントを探せませんでした。",
  noUser: "存在しないユーザーです。",
  invaildUser: "認証されてないユーザーです。",
  invaildPassword: "パスワードが間違いました。",
  commentError: "コメント呼び出しに失敗しました。",
  likesError: "「いいね」リスト呼び出しに失敗しました。",
  recommendPhotoError: "おすすめ写真呼び出しに失敗しました。",
  recommendUserError: "おすすめユーザー呼び出しに失敗しました。",
  existUser: "既に存在するメールアドレスまたはニックネームです。",
  createAccountError: "アカウント生成に失敗しました。",
  editProfileError: "プロフィール更新に失敗しました。",
  noFollowUser: "フォローするユーザーが存在しません。",
  unfollowUserError: "ユーザーアンフォローに失敗しました。",
  seeUsersError: "全体ユーザー呼び出しに失敗しました。",
};
